### ISSUE TITLE
[Environment] Since each version of pytorch and CUDA are low, it doesn't work on RTX 3090 TI 

### ISSUE THREAD

**Issue by comeeasy** [yael-vinker/SceneSketch#6]
Specs of my server:
  GPU: two RTX 3090 TIs
  OS: Ubuntu 20.04.3 LTS

I'm following the instructions in the README file.
Docker images, git repos, and the weight of UNet are successfully installed.
The problem is that it shows following errors at preprocessing image step.

Error log:
==============================================================================
```
root@46082cf559f2:~/SceneSketch# python preprocess_images.py 
Detectron v2 is not installed
Producing mask using U2Net....
/home/miniconda/envs/habitat/lib/python3.7/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "preprocess_images.py", line 207, in <module>
    mask = get_U2Net_mask(args.top_path, im_name, device, args.use_gpu)
  File "preprocess_images.py", line 82, in get_U2Net_mask
    d1, d2, d3, d4, d5, d6, d7 = net(input_im_trans.to(device))
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/SceneSketch/U2Net_/model/u2net.py", line 361, in forward
    hx1 = self.stage1(hx)
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/SceneSketch/U2Net_/model/u2net.py", line 65, in forward
    hxin = self.rebnconvin(hx)
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/SceneSketch/U2Net_/model/u2net.py", line 16, in forward
    xout = self.relu_s1(self.bn_s1(self.conv_s1(hx)))
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
-----
If dockerfile is included in this repo, I could solve this problem by modifying
 dockerfile.

Could you provide a Dockerfile?

**Comment by kartikeyporwal** [comment]
Hi @comeeasy, were you able to run this successfully?

**Comment by comeeasy** [comment]
Hi @kartikeyporwal,
Thank you for your kindness!

Actually, I resolved this problem a while ago by installing a newer version of PyTorch. 
It was a silly issue..

We can close this issue now.

**Comment by comeeasy** [comment]
Hi @kartikeyporwal,
Thank you for your kindness!

Actually, I resolved this problem a while ago by installing a newer version of PyTorch.
It was a silly issue..

We can close this issue now.
